package year25

import core.DayTest

private val defaultInput = """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
""".trimIndent()

class Year25Day7Test : DayTest<List<String>, Int, Long>(
    Year25Day7::class.java,
    listOf(
        defaultInput to 21
    ),
    listOf(
        defaultInput to 40
    )
)
