package year24

import core.DayTest

private val defaultInput = """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
""".trimIndent()

class Year24Day8Test : DayTest<List<String>, Int, Int>(
    Year24Day8::class.java,
    listOf(
        defaultInput to 14
    ),
    listOf(
        defaultInput to 34
    )
)
